--Create tables for each of the 6 CSV files 

CREATE TABLE TITLES(
	Title_ID VARCHAR(20) NOT NULL,
	Title VARCHAR(30) NOT NULL,
	PRIMARY KEY (Title_ID)
);

SELECT * FROM TITLES


CREATE TABLE EMPLOYEES(
	Emp_no INT NOT NULL PRIMARY KEY,
	Emp_title_ID VARCHAR(30) NOT NULL,
	Birth_date VARCHAR(20) NOT NULL,
	First_name VARCHAR(20) NOT NULL,
	Last_name VARCHAR(20) NOT NULL,
	Sex VARCHAR(10) NOT NULL, 
	Hire_date DATE NOT NULL,
	FOREIGN KEY (Emp_title_ID) REFERENCES TITLES(Title_ID)
);

SELECT * FROM EMPLOYEES


CREATE TABLE DEPARTMENTS(
	Dept_no VARCHAR(15) NOT NULL,
	Dept_name VARCHAR(20) NOT NULL,
	PRIMARY KEY (Dept_no)
);

SELECT * FROM DEPARTMENTS


CREATE TABLE DEPT_MANAGER(
	Dept_no VARCHAR(15) NOT NULL,
	Emp_no INT NOT NULL,
	FOREIGN KEY (Emp_no) REFERENCES EMPLOYEES(Emp_no),
	FOREIGN KEY (Dept_no) REFERENCES DEPARTMENTS(Dept_no),
	PRIMARY KEY (Dept_no, Emp_no)
);

SELECT * FROM DEPT_MANAGER

CREATE TABLE DEPT_EMP(
	Emp_no INT NOT NULL,
	Dept_no VARCHAR(15) NOT NULL,
	FOREIGN KEY (Emp_no) REFERENCES EMPLOYEES(Emp_no),
	FOREIGN KEY (Dept_no) REFERENCES DEPARTMENTS(Dept_no),
	PRIMARY KEY (Emp_no, Dept_no)
);

SELECT * FROM DEPT_EMP

CREATE TABLE SALARIES(
	Emp_no INT NOT NULL PRIMARY KEY,
	Salary INT NOT NULL,
	FOREIGN KEY (Emp_no) REFERENCES EMPLOYEES(Emp_no)
);

SELECT * FROM SALARIES